spring:
  application:
    name: zipkin

logging:
  level.org.springframework.cloud: DEBUG

zipkin:
  storage:
    type: mem
server:
  port: 9411

management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true